name: build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-26.04]
    steps:
      - uses: actions/checkout@v7
      - run: lscpu
      - run: make -j2
      - run: ./unit-test
      - run: ./avx-turbo --no-pin --max-threads 2
